### ISSUE TITLE
Throwing a error and not working

### ISSUE THREAD

**Issue by CyberWarden** [oldnapalm/GTACoop#19] opened 2024-09-21 20:41 UTC
[13:37:52] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[13:37:52] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[13:37:52] [DEBUG] Loading scripts from D:\SteamLibrary\steamapps\common\Grand Theft Auto V(modded)\scripts ...
[13:37:52] [DEBUG] Loading assembly GTACoOp.dll ...
[13:37:52] [INFO] Found 2 script(s) in GTACoOp.dll resolved to API 3.6.0.
[13:37:52] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
[13:37:52] [INFO] Found 0 script(s) in LemonUI.SHVDN3.dll.
[13:37:52] [DEBUG] Loading assembly Lidgren.Network.MultiTarget.dll ...
[13:37:52] [INFO] Found 0 script(s) in Lidgren.Network.MultiTarget.dll.
[13:37:52] [DEBUG] Loading assembly MaxMind.Db.dll ...
[13:37:53] [INFO] Found 0 script(s) in MaxMind.Db.dll.
[13:37:53] [DEBUG] Loading assembly MaxMind.GeoIP2.dll ...
[13:37:53] [INFO] Found 0 script(s) in MaxMind.GeoIP2.dll.
[13:37:53] [DEBUG] Loading assembly NAudio.dll ...
[13:37:53] [INFO] Found 0 script(s) in NAudio.dll.
[13:37:53] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[13:37:53] [INFO] Found 0 script(s) in Newtonsoft.Json.dll.
[13:37:53] [DEBUG] Loading assembly protobuf-net.dll ...
[13:37:53] [INFO] Found 0 script(s) in protobuf-net.dll.
[13:37:53] [DEBUG] Instantiating script GTACoOp.Main ...
[13:37:54] [ERROR] Failed to instantiate script GTACoOp.Main because constructor threw an exception: System.TypeInitializationException: The type initializer for 'SHVDN.NativeMemory' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SHVDN.NativeMemory..cctor()
   --- End of inner exception stack trace ---
   at SHVDN.NativeMemory.get_CellEmailBcon()
   at GTA.UI.Notification.Show(String message, Boolean blinking)
   at GTACoOp.Main..ctor()
[13:37:54] [DEBUG] Instantiating script GTACoOp.PedThread ...
[13:37:54] [INFO] Started script GTACoOp.PedThread.

**Comment by oldnapalm** [comment] 2024-09-21 20:44
Duplicate of #10

**Closed by oldnapalm** 2024-09-21 20:44 UTC

**Comment by CyberWarden** [comment] 2024-09-21 20:55
Fixed by getting a nightly build of ScriptHookVDotNet.  Sorry to bother you.
https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases
